//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatalayerMonthlyBills
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public Bill()
        {
            this.Payment = new HashSet<Payment>();
        }
    
        public int Id { get; set; }
        public string BillName { get; set; }
        public Nullable<decimal> Bal { get; set; }
        public Nullable<decimal> minPayment { get; set; }
        public string DueDate { get; set; }
        public string Login { get; set; }
        public string PasswordHint { get; set; }
    
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
